
export const screenNames = {
    SIGNIN : "Signin",
    SIGNUP : "Signup",
    OTP_SCREEN : "OTPscreen",
    GOOGLE_VERIFICATION_CODE : "GoogleVerificationCode",
    FORGOT_PASSWORD : "Forgot Password",
    VERIFY_EMAIL : "Verify Email",
    CHANGE_PASSWORD :"ChangePassword",
    DASHBOARD :"Dashboard",
    ABOUT :"About",
    SETTINGS : "Settings",
    SECURITY : "Security",
    BANK_ACCOUNT_DETAILS : "Bank Account Details",
    HOME : "Home",
    MARKETS : "Markets",
    TRADES :"Trades",
    WALLET : "Wallet",
    ACCOUNT : "Account",
    ORDERS : "Orders",
    ORDERS_HISTORY : "OrdersHistory",
    DEPOSIT: 'Deposit',
    WITHDRAW: 'Withdraw',
    UPI: 'UPI',
    NOTIFICATIONS: 'Notifications',
    IMPS:'IMPS / NEFT / RTGS',
    CHANGE_PASSWORD_SETTINGS: 'Change Password',
    DEVICE_MANAGEMENT:'Device Management',
    SET_ANTI_SPOOF:'Set Anti-Spoofing Code',
    GOOGLE_AUTHENTICATOR: 'Google Authenticator',
    TWO_FACTOR_AUTHENTICATION: ' 2 Factor Authentication'

}