export const TYPES = {
    EMAIL_INPUT: "EMAIL_INPUT",
    PASSWORD_INPUT: "PASSWORD_INPUT",

    ADD_DELETE_FAVOURITE:'ADD_DELETE_FAVOURITE',
    ADD_MARKET_DATA:'ADD_MARKET_DATA',
    UPDATE_MARKET_DATA_ITEM:'UPDATE_MARKET_DATA_ITEM',
    CHANGE_MARKET_PAIR_DATA:'ADD_MARKET_DATA',
    TRIGGER_SOCKET_FOR_MARKET:'TRIGGER_SOCKET_FOR_MARKET',

    ADD_DEPTH_SUBS_DATA:'ADD_DEPTH_SUBS_DATA',
    TRIGGER_SOCKET_FOR_DEPTH_SUBS:'TRIGGER_SOCKET_FOR_DEPTH_SUBS',

    ADD_DEVICE_ID: 'ADD_DEVICE_ID',
    SAVE_USER_ID:'SAVE_USER_ID',
    SAVE_IP: 'SAVE_IP',
    SAVE_AUTH_ATTRIBUTES:'SAVE_AUTH_ATTRIBUTES',

    FETCHED_WALLET_BALANCE: 'FETCHED_WALLET_BALANCE',
    FETCHED_WALLET_ASSETS: 'FETCHED_WALLET_ASSETS'
    
}
