export const TYPES = {
    EMAIL_INPUT: "EMAIL_INPUT",
    PASSWORD_INPUT: "PASSWORD_INPUT",

    ADD_DELETE_FAVOURITE:'ADD_DELETE_FAVOURITE',
    ADD_MARKET_DATA:'ADD_MARKET_DATA',
    CHANGE_MARKET_PAIR_DATA:'ADD_MARKET_DATA',

    ADD_DEVICE_ID: 'ADD_DEVICE_ID',
    SAVE_USER_ID:'SAVE_USER_ID',
    SAVE_IP: 'SAVE_IP',
    SAVE_AUTH_ATTRIBUTES:'SAVE_AUTH_ATTRIBUTES'
    
}