export const TYPES = {
    EMAIL_INPUT: "EMAIL_INPUT",
    PASSWORD_INPUT: "PASSWORD_INPUT",

    ADD_DELETE_FAVOURITE:'ADD_DELETE_FAVOURITE',
    ADD_MARKET_DATA:'ADD_MARKET_DATA',
    ADD_MARKET_LIST:'ADD_MARKET_LIST',
    UPDATE_MARKET_DATA_ITEM:'UPDATE_MARKET_DATA_ITEM',
    CHANGE_MARKET_PAIR_DATA:'ADD_MARKET_DATA',
    TRIGGER_SOCKET_FOR_MARKET:'TRIGGER_SOCKET_FOR_MARKET',
    STORE_INDEX_PRICE:'STORE_INDEX_PRICE',
    STORE_CURRENCIES:'STORE_CURRENCIES',
    SET_ACTIVE_TRADE_PAIR:'SET_ACTIVE_TRADE_PAIR',

    ADD_DEPTH_SUBS_DATA:'ADD_DEPTH_SUBS_DATA',
    ADD_DEPTH_ASKS:'ADD_DEPTH_ASKS',
    ADD_DEPTH_BIDS:'ADD_DEPTH_BIDS',
    CLEAR_ALL:'CLEAR_ALL',
    TRIGGER_SOCKET_FOR_DEPTH_SUBS:'TRIGGER_SOCKET_FOR_DEPTH_SUBS',

    ADD_DEALS_DATA:'ADD_DEALS_DATA',
    
    ADD_KLINE_DATA:'ADD_KLINE_DATA',
    ADD_KLINE_QUERY_DATA:'ADD_KLINE_QUERY_DATA',
    UPDATE_KLINE_BOOL:'UPDATE_KLINE_BOOL',
    EMPTY_KLINE_DATA:'EMPTY_KLINE_DATA',

    ADD_DEVICE_ID: 'ADD_DEVICE_ID',
    SAVE_USER_ID:'SAVE_USER_ID',
    SAVE_IP: 'SAVE_IP',
    SAVE_AUTH_ATTRIBUTES:'SAVE_AUTH_ATTRIBUTES',

    FETCHED_WALLET_BALANCE: 'FETCHED_WALLET_BALANCE',
    FETCHED_WALLET_ASSETS: 'FETCHED_WALLET_ASSETS',

    ADD_NEW_BANK:"ADD_NEW_BANK",
    DELETE_NEW_BANK:"DELETE_NEW_BANK",
    
}
